// <auto-generated />
namespace CadeMeuPet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NoCEP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoCEP));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111130152_NoCEP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
